window.LESSONS=[
{id:1,title:'Required tools',goal:'Recognize the software and hardware required for the project.',actions:[['view','tool'],['tools',[['🛠️','Android Studio'],['📦','Android SDK'],['☕','Java/JDK'],['⚙️','Gradle'],['K','Kotlin'],['🌐','GitHub Pages'],['📱','Android phone'],['🔌','USB cable']]],['caption','These tools are needed before you begin.'],['explain','Android Studio is the development environment. The SDK builds the app. Java 17 and Kotlin compile it. GitHub Pages hosts the LiaScript course.'],['result','All required tools are identified.']]},
{id:2,title:'Create Android Studio project',goal:'Create an Empty Activity project with the correct settings.',actions:[['view','desktop'],['caption','Open Android Studio.'],['pointer','12%','24%'],['click'],['view','android'],['tree','New Project\n  → Empty Activity / Empty Views Activity'],['code','New Project','Project name: A1.1 German Part 1\nPackage name: io.github.masubmakhdoom.a1part1modern\nLanguage: Kotlin\nMinimum SDK: 23'],['meaning','Minimum SDK 23 means Android 6.0 or newer.'],['result','The Kotlin Android project is created.']]},
{id:3,title:'Open project in Terminal',goal:'Use cd to enter the Android project folder.',actions:[['view','desktop'],['caption','Open Terminal.'],['pointer','29%','24%'],['click'],['view','terminal'],['type','cd "/Users/masubmakhdoom/AndroidStudioProjects/A11GermanPart1"'],['enter','Current directory changed to A11GermanPart1'],['meaning','cd means change directory.'],['result','Terminal is now inside the project folder.']]},
{id:4,title:'Project-level Gradle',goal:'Place plugin versions in build.gradle.kts.',actions:[['view','android'],['tree','A11GermanPart1\n├── app\n├── build.gradle.kts  ← project level\n└── settings.gradle.kts'],['code','build.gradle.kts','plugins {\n    id("com.android.application") version "8.7.3" apply false\n    id("org.jetbrains.kotlin.android") version "2.0.21" apply false\n}'],['meaning','Do not put android { ... } in this file.'],['result','Plugin versions are configured.']]},
{id:5,title:'App-level Gradle',goal:'Configure SDK values and Java 17.',actions:[['view','android'],['tree','A11GermanPart1\n└── app\n    └── build.gradle.kts  ← app level'],['code','app/build.gradle.kts','android {\n    namespace = "io.github.masubmakhdoom.a1part1modern"\n    compileSdk = 35\n    defaultConfig {\n        minSdk = 23\n        targetSdk = 35\n        versionCode = 1\n        versionName = "1.0"\n    }\n    compileOptions {\n        sourceCompatibility = JavaVersion.VERSION_17\n        targetCompatibility = JavaVersion.VERSION_17\n    }\n}\nkotlin { jvmToolchain(17) }'],['meaning','compileSdk builds the app; targetSdk declares the target; minSdk sets the oldest supported version.'],['result','The app module uses SDK 35 and Java 17.']]},
{id:6,title:'Fix JVM mismatch',goal:'Make Java and Kotlin use compatible versions.',actions:[['view','android'],['build','ERROR: Inconsistent JVM-target compatibility\nJava = 1.8\nKotlin = 21'],['caption','The Java and Kotlin targets do not match.'],['code','app/build.gradle.kts','compileOptions {\n  sourceCompatibility = JavaVersion.VERSION_17\n  targetCompatibility = JavaVersion.VERSION_17\n}\nkotlin { jvmToolchain(17) }'],['build','✓ Java target = 17\n✓ Kotlin target = 17\nBUILD CONFIGURATION VALID'],['result','Both compilers now use Java 17.']]},
{id:7,title:'Create themes',goal:'Create normal and night-mode theme files.',actions:[['view','android'],['tree','app/src/main/res\n├── values/themes.xml\n└── values-night/themes.xml'],['code','values/themes.xml','<resources>\n  <style name="Theme.A11GermanPart1" parent="@android:style/Theme.Material.Light.NoActionBar">\n    <item name="android:windowNoTitle">true</item>\n    <item name="android:statusBarColor">#FFFFFF</item>\n  </style>\n</resources>'],['meaning','values is normal mode; values-night is dark mode.'],['result','Light and dark themes are available.']]},
{id:8,title:'AndroidManifest.xml',goal:'Add internet permission, app name and launcher activity.',actions:[['view','android'],['tree','app/src/main\n└── AndroidManifest.xml'],['code','AndroidManifest.xml','<manifest xmlns:android="http://schemas.android.com/apk/res/android">\n  <uses-permission android:name="android.permission.INTERNET" />\n  <application android:theme="@style/Theme.A11GermanPart1" android:label="A1 German Modern Online">\n    <activity android:name=".MainActivity" android:exported="true">\n      <intent-filter>\n        <action android:name="android.intent.action.MAIN" />\n        <category android:name="android.intent.category.LAUNCHER" />\n      </intent-filter>\n    </activity>\n  </application>\n</manifest>'],['meaning','INTERNET permission is required for the online LiaScript course.'],['result','Android knows the app name, permission and first activity.']]},
{id:9,title:'MainActivity WebView',goal:'Load the LiaScript course inside Android WebView.',actions:[['view','android'],['tree','app/src/main/java/io/github/masubmakhdoom/a1part1modern\n└── MainActivity.kt'],['code','MainActivity.kt','webView = WebView(this)\nsetContentView(webView)\nwebView.webViewClient = WebViewClient()\nwebView.webChromeClient = WebChromeClient()\nval settings = webView.settings\nsettings.javaScriptEnabled = true\nsettings.domStorageEnabled = true\nsettings.databaseEnabled = true\nsettings.mediaPlaybackRequiresUserGesture = false\nwebView.loadUrl("https://masub27.github.io/a1-iphone-part1/")'],['meaning','JavaScript and DOM storage are needed by LiaScript.'],['result','The app opens the online LiaScript course.']]},
{id:10,title:'Build the APK',goal:'Clean and build a debug APK.',actions:[['view','terminal'],['type','./gradlew clean'],['enter','BUILD SUCCESSFUL'],['type','./gradlew assembleDebug'],['enter','Compiling Kotlin...\nProcessing resources...\nPackaging APK...\nBUILD SUCCESSFUL'],['meaning','assembleDebug creates an installable test APK.'],['result','app-debug.apk has been created.']]},
{id:11,title:'Copy APK to Desktop',goal:'Move the APK to an easy-to-find location.',actions:[['view','terminal'],['type','cp app/build/outputs/apk/debug/app-debug.apk "/Users/masubmakhdoom/Desktop/A1_German_Modern_Online.apk"'],['enter','APK copied successfully'],['view','desktop'],['caption','The APK now appears on the Desktop.'],['result','The APK is ready for transfer.']]},
{id:12,title:'Install on phone',goal:'Transfer and install the APK.',actions:[['view','phone'],['phone','Receiving A1_German_Modern_Online.apk...'],['wait',1200],['phone','Install this application?\n\n[ Cancel ]   [ Install ]'],['wait',1200],['phone','Installing...\n██████████ 100%'],['wait',1200],['phone','A1 German Modern Online\n\nApp installed successfully'],['result','The app is installed.']]},
{id:13,title:'Test the app',goal:'Check all important app functions.',actions:[['view','phone'],['phone','Testing checklist\n\n✓ App opens\n✓ Course loads\n✓ No white screen\n✓ Audio works\n✓ Video works\n✓ Links open\n✓ Quizzes work\n✓ Back button works\n✓ Screen is clear\n✓ Internet available'],['result','All main functions have been checked.']]},
{id:14,title:'Common errors',goal:'Recognize and fix the documented problems.',actions:[['view','android'],['build','ERROR 1: android { ... } in wrong file\nFix: Move it to app/build.gradle.kts.'],['wait',1500],['build','ERROR 2: MaterialComponents theme not found\nFix: Use a built-in Android theme.'],['wait',1500],['build','ERROR 3: JVM target mismatch\nFix: Set Java and Kotlin to 17.'],['wait',1500],['build','ERROR 4: White WebView screen\nFix: Use the GitHub Pages online URL.'],['result','The learner can diagnose the main errors.']]}
];
